"""
Generate the LaTeX data fragments for the AGC reassessment report.

NO numbers are hand-written in the report. This script reads the pipeline's
own outputs and emits, into report/generated/:
  - macros.tex          : \newcommand definitions for every inline number
  - results_table.tex   : the per-group MSR / COD table (existing vs new)
  - equity_income.tex   : MSR / COD by Census median-income quintile
  - equity_minority.tex : MSR / COD by Census-tract pct_minority band

report.tex \input's these, so every figure in the prose and tables traces
back to a generated value. Re-run this whenever the models/ratio study change:
    python report/build_report.py

Sources (all generated by the pipeline, none hand-edited):
  - data/.../out/models/<group>/reports/ratio_study.md   (MSR, COD, breakdowns)
  - data/.../out/models/<group>/main/model_ensemble.pickle (VEI)
  - output/residential_predictions.csv                    (county under-assessment)
"""
import os, re, sys, glob
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
import pandas as pd
pd.options.future.infer_string = False
import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OAK = os.path.abspath("C:/projects/openavmkit")
if OAK not in sys.path:
    sys.path.insert(0, OAK)
MODELS = os.path.join(REPO, "data", "us-pa-allegheny", "out", "models")
GEN = os.path.join(os.path.dirname(os.path.abspath(__file__)), "generated")
os.makedirs(GEN, exist_ok=True)

# group key -> (display label, LaTeX-macro-safe camelCase suffix, is_residential)
GROUPS = [
    ("residential_single_family_suburban",        "Single-Family Suburban",        "suburban",    True),
    ("residential_single_family_urban",           "Single-Family Urban",           "urban",       True),
    ("residential_single_family_suburban_prewar", "Single-Family Suburban Pre-War","prewar",      True),
    ("residential_multi_family",                   "Multi-Family",                  "multifamily", True),
    ("commercial",                                 "Commercial",                    "commercial",  False),
]

# --- parse the canonical ratio-study markdown report ---------------------------

def _report_text(group):
    p = os.path.join(MODELS, group, "reports", "ratio_study.md")
    return open(p, encoding="utf-8").read() if os.path.exists(p) else ""

def _overall(text, trimmed=True):
    """(county_MSR, our_MSR, county_COD, our_COD) from the improved-overall block."""
    tag = r"Improved property only \(trimmed\)" if trimmed else r"Improved property only \(untrimmed\)"
    m = re.search(tag + r"(.*?)(?:####|\Z)", text, re.S)
    if not m:
        return (None, None, None, None)
    b = m.group(1)
    mr = re.search(r"Median ratio \|\s*([\d.]+)\s*\|\s*([\d.]+)", b)
    cod = re.search(r"\| COD \|\s*([\d.]+)\s*\|\s*([\d.]+)", b)
    cnt = re.search(r"\| Count \|\s*([\d,]+)\s*\|\s*([\d,]+)", b)
    return (mr and mr.group(1), mr and mr.group(2), cod and cod.group(1), cod and cod.group(2),
            cnt and cnt.group(2))

def _breakdown_rows(text, by):
    """[(label, count, our_MSR, our_COD_trim)] for a breakdown under 'Our results'."""
    sub = text[text.find("### Our results"):]
    m = re.search(rf"#### By {by}.*?(?=\n#### |\n### |\Z)", sub, re.S)
    if not m:
        return []
    out = []
    for line in m.group(0).splitlines():
        cells = [c.strip() for c in line.split("|")[1:-1]]
        # a data row has a numeric Count in column 2; this excludes the header
        # row, the |---| separator, and the "N other groups with count < 15"
        # catch-all row.
        if len(cells) >= 6 and cells[1].replace(",", "").isdigit() and "other group" not in cells[0].lower():
            label = cells[0].split("<br>")[0].strip()
            out.append((label, cells[1], cells[2], cells[5]))
    return out


def _esc(s):
    """Escape LaTeX specials in extracted label text (e.g. the % in '75-100%')."""
    for a, b in [("%", r"\%"), ("&", r"\&"), ("_", r"\_"), ("#", r"\#"), ("$", r"\$")]:
        s = s.replace(a, b)
    return s

# --- VEI from the trained ensemble pickles -------------------------------------

def _vei(group):
    import pickle
    from openavmkit.vertical_equity_study import get_vertical_equity_scores
    p = os.path.join(MODELS, group, "main", "model_ensemble.pickle")
    if not os.path.exists(p):
        return None
    res = pickle.load(open(p, "rb"))
    df = getattr(res, "df_test", None)
    if df is None or "sale_price_time_adj" not in df.columns or "prediction" not in df.columns:
        return None
    d = pd.DataFrame({"s": df["sale_price_time_adj"].values, "v": df["prediction"].values})
    d = d[np.isfinite(d["s"]) & (d["s"] > 0) & np.isfinite(d["v"])]
    try:
        return get_vertical_equity_scores(d, "s", "v")["vei"]
    except Exception:
        return None

# --- county-wide under-assessment from the published predictions ---------------

def _county_underassessment():
    p = os.path.join(REPO, "output", "residential_predictions.csv")
    if not os.path.exists(p):
        return None, None
    df = pd.read_csv(p)
    new = pd.to_numeric(df["NEW_ASSESSMENT_TOTAL"], errors="coerce").sum()
    cur = pd.to_numeric(df["CURRENT_ASSESSMENT_TOTAL"], errors="coerce").sum()
    ratio = new / cur if cur else None
    return ratio, (100.0 / ratio if ratio else None)  # ratio (e.g. 2.08), pct-of-market (e.g. 48)

# --- LaTeX emission ------------------------------------------------------------

def _texnum(x, dec=2):
    return "--" if x is None else (f"{x:.{dec}f}" if isinstance(x, float) else str(x))

macros, table_rows, header = [], [], (
    "% GENERATED by report/build_report.py -- do not edit by hand.\n"
    "% Re-run `python report/build_report.py` to refresh.\n"
)

def macro(name, value):
    macros.append(rf"\newcommand{{\{name}}}{{{value}}}")

# collect per-group
data = {}
for key, label, suf, is_res in GROUPS:
    t = _report_text(key)
    cMSR, oMSR, cCOD, oCOD, n = _overall(t, trimmed=True)
    vei = _vei(key)
    data[key] = dict(label=label, suf=suf, is_res=is_res, n=n,
                     cMSR=cMSR, oMSR=oMSR, cCOD=cCOD, oCOD=oCOD, vei=vei)
    Suf = suf[0].upper() + suf[1:]
    if oMSR: macro(f"msrNew{Suf}", oMSR)
    if cMSR: macro(f"msrCounty{Suf}", cMSR)
    if oCOD: macro(f"codNew{Suf}", oCOD)
    if cCOD: macro(f"codCounty{Suf}", cCOD)
    if vei is not None: macro(f"veiNew{Suf}", f"{vei:+.0f}")
    if n: macro(f"sales{Suf}", n)

# total modeled parcels = sum of each group's universe (fast: parquet row count)
total_parcels = 0
for key, *_ in GROUPS:
    pq = os.path.join(MODELS, key, "main", "ensemble", "pred_universe.parquet")
    if os.path.exists(pq):
        total_parcels += len(pd.read_parquet(pq, columns=["key"]))
if total_parcels:
    macro("totalParcels", f"{total_parcels:,}")
macro("numModelGroups", str(len(GROUPS)))

ratio, pct = _county_underassessment()
if ratio: macro("countyUnderRatio", f"{ratio:.2f}")
if pct:   macro("countyUnderPct", f"{pct:.0f}")
macro("valuationDate", "2026-01-01")
macro("studyPeriod", "2025-01-01 to 2026-01-01")

# results table (booktabs)
rows = "\n".join(
    rf"{d['label']} & {d['n'] or '--'} & {d['cMSR'] or '--'} & {d['oMSR'] or '--'} "
    rf"& {d['cCOD'] or '--'} & {d['oCOD'] or '--'} & {_texnum(d['vei'],0) if d['is_res'] else '--'} \\"
    for d in data.values()
)
results_table = header + r"""\begin{tabular}{lrrrrrr}
\toprule
& & \multicolumn{2}{c}{Median sales ratio} & \multicolumn{2}{c}{COD (trimmed)} & VEI \\
\cmidrule(lr){3-4}\cmidrule(lr){5-6}
Model group & Sales & County & New & County & New & New \\
\midrule
""" + rows + r"""
\bottomrule
\end{tabular}
"""

# equity breakdown tables (suburban_prewar is the exemplar; richest gradient)
def equity_table(by, caption_macro):
    rows = []
    for key, label, suf, is_res in GROUPS:
        if not is_res:
            continue
        br = _breakdown_rows(_report_text(key), by)
        if not br:
            continue
        # lowest and highest strata (first and last real bands)
        lo, hi = br[0], br[-1]
        rows.append(rf"{_esc(label)} & {_esc(lo[0])} & {lo[2]} & {lo[3]} & {_esc(hi[0])} & {hi[2]} & {hi[3]} \\")
    return header + r"""\begin{tabular}{lcccccc}
\toprule
& \multicolumn{3}{c}{Lowest stratum} & \multicolumn{3}{c}{Highest stratum} \\
\cmidrule(lr){2-4}\cmidrule(lr){5-7}
Model group & Band & MSR & COD & Band & MSR & COD \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
"""

with open(os.path.join(GEN, "macros.tex"), "w", encoding="utf-8") as f:
    f.write(header + "\n".join(macros) + "\n")
with open(os.path.join(GEN, "results_table.tex"), "w", encoding="utf-8") as f:
    f.write(results_table)
with open(os.path.join(GEN, "equity_income.tex"), "w", encoding="utf-8") as f:
    f.write(equity_table("median_income", "byIncome"))
with open(os.path.join(GEN, "equity_minority.tex"), "w", encoding="utf-8") as f:
    f.write(equity_table("pct_minority", "byMinority"))

print(f"Wrote {len(macros)} macros + 3 tables to {GEN}")
print("\n--- macros.tex ---")
print("\n".join(macros))
